# Generated by Django 3.1.7 on 2021-06-23 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorId', models.IntegerField(max_length=4)),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookId', models.IntegerField(max_length=4)),
                ('title', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='webapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublisherId', models.IntegerField(max_length=4)),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=20, null=True)),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='webapp.book')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberId', models.IntegerField(max_length=4)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40, null=True)),
                ('phone', models.IntegerField(max_length=10)),
                ('NoOfBooksBorrowed', models.IntegerField(max_length=4, null=True)),
                ('fine', models.IntegerField(max_length=4, null=True)),
                ('book', models.ManyToManyField(blank=True, related_name='members', to='webapp.Book')),
            ],
        ),
    ]
