# Generated by Django 3.1.7 on 2021-06-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='AuthorId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='MemberId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='NoOfBooksBorrowed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='fine',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='PublisherId',
            field=models.IntegerField(),
        ),
    ]
