# Generated by Django 3.1.7 on 2021-06-23 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210623_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('CarNo', models.IntegerField(primary_key=True, serialize=False)),
                ('CarName', models.CharField(max_length=30)),
                ('CarModel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.IntegerField(primary_key=True, serialize=False)),
                ('PassportNo', models.CharField(max_length=15)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('RentalNO', models.IntegerField(primary_key=True, serialize=False)),
                ('Timeout', models.DateField()),
                ('TimeReturn', models.DateField()),
                ('CarNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.car')),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaffID', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('PhoneNo', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='member',
            name='book',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddField(
            model_name='rental',
            name='StaffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.staff'),
        ),
        migrations.AddField(
            model_name='car',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carstaff', to='webapp.staff'),
        ),
    ]
